server:
  port: ${PORT:8011}

spring:
  application:
    name: chat-controller
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: CONFIG-SERVER
  config:
    import: optional:configserver:RANDOMVALUE?
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${JWT_PROVIDER_URI:http://localhost:8180/realms/ChatV2Realm/protocol/openid-connect/certs}
  kafka:
    producer:
      clientId: ${spring.application.name}
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.faust.chat.command.CommandSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8091/eureka/}
  instance:
    instanceId: ${random.value}
    preferIpAddress: true