front:
  origin: ${FRONT_URL:http://localhost:4200}

server:
  port: ${PORT:8001}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8091/eureka/}
  instance:
    instanceId: ${random.value}
    preferIpAddress: true

spring:
  application:
    name: gateway
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${JWT_PROVIDER_URI:http://localhost:8180/realms/ChatV2Realm/protocol/openid-connect/certs}
  cloud:
    gateway:
      routes:
        - id: eureka
          uri: ${EUREKA_ROUTE_URL:http://localhost:8091}
          predicates:
            - Path=/eureka/**
            - Method=GET
          filters:
            - RewritePath=/eureka(?<remaining>/?.*), /$\{remaining}