services:
  discovery:
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_started
      keycloak:
        condition: service_healthy

  channel-repository:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://postgres:5432/postgres

  chat-repository:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://postgres:5432/postgres

  gateway:
    environment:
      JWT_PROVIDER_URI: http://keycloak:8080/realms/ChatV2Realm/protocol/openid-connect/certs
      FRONT_URL: "http://localhost:4200"

  keycloak-repository:
    environment:
      KEYCLOAK_URI: http://keycloak:8080
      KEYCLOAK_REALM: ChatV2Realm
      KEYCLOAK_ID: cv2-backend
      KEYCLOAK_SECRET: GJJuJksZfQUpiAV4X8QprPXmMDx0B0Dq

  configuration-server:
    environment:
      KAFKA_HOSTNAME: kafka
      KAFKA_PORT: 29092