services:
  discovery:
    image: discovery-local:latest
    expose:
      - 8091

  configuration-server:
    image: shared-config-local:latest
    environment:
      EUREKA_URL: http://discovery:8091/eureka/
    expose:
      - 8092

  channel-controller:
    image: channel-controller-local:latest
    environment:
      EUREKA_URL: http://discovery:8091/eureka/
    expose:
      - 8012
    depends_on:
      - discovery
      - configuration-server

  channel-repository:
    image: channel-repository-local:latest
    environment:
      EUREKA_URL: http://discovery:8091/eureka/
    expose:
      - 8022
    depends_on:
      - discovery
      - configuration-server

  chat-controller:
    image: chat-controller-local:latest
    environment:
      EUREKA_URL: http://discovery:8091/eureka/
    expose:
      - 8011
    depends_on:
      - discovery
      - configuration-server

  chat-repository:
    image: chat-repository-local:latest
    environment:
      EUREKA_URL: http://discovery:8091/eureka/
    expose:
      - 8021
    depends_on:
      - discovery
      - configuration-server

  chat-request-filter:
    image: chat-request-filter-local:latest
    environment:
      EUREKA_URL: http://discovery:8091/eureka/
    expose:
      - 8031
    depends_on:
      - discovery
      - configuration-server

  keycloak-repository:
    image: keycloak-repository-local:latest
    environment:
      EUREKA_URL: http://discovery:8091/eureka/
    expose:
      - 8023
    depends_on:
      - discovery
      - configuration-server

  sse:
    image: sse-local:latest
    environment:
      EUREKA_URL: http://discovery:8091/eureka/
    expose:
      - 8099
    depends_on:
      - discovery
      - configuration-server

  user-repository:
    image: user-repository-local:latest
    environment:
      EUREKA_URL: http://discovery:8091/eureka/
    expose:
      - 8024
    depends_on:
      - discovery
      - configuration-server

  user-sse:
    image: user-sse-local:latest
    environment:
      EUREKA_URL: http://discovery:8091/eureka/
    expose:
      - 8013
    depends_on:
      - discovery
      - configuration-server

  gateway:
    image: gateway-local:latest
    environment:
      EUREKA_URL: http://discovery:8091/eureka/
      EUREKA_ROUTE_URL: http://discovery:8091
      JWT_PROVIDER_URI:
    expose:
      - 8001
    ports:
      - 8001:8001
    depends_on:
      - discovery
      - configuration-server
      - channel-controller
      - channel-repository
      - chat-controller
      - chat-repository
      - chat-request-filter
      - keycloak-repository
      - sse
      - user-repository
      - user-sse
