rootProject.name = "chat"
include("channel-common")
include("chat-common")
include("discovery")
include("shared-config")
include("channel-controller")
include("channel-repository")
include("chat-controller")
include("chat-repository")
include("gateway")
include("common-repository")
include("sse")
include("chat-request-filter")
include("keycloak-repository")
include("sse-common")
include("user-sse")
include("user-repository")
