server:
  port: ${PORT:8099}

spring:
  application:
    name: sse
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: CONFIG-SERVER
  config:
    import: optional:configserver:RANDOMVALUE?
  kafka:
    consumer:
      clientId: ${spring.application.name}
      groupId: ${spring.application.name}-group
      keyDeserializer: org.apache.kafka.common.serialization.StringSerializer
      valueDeserializer: org.apache.kafka.common.serialization.StringSerializer
      auto-offset-reset: earliest

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8091/eureka/}
  instance:
    instanceId: ${random.value}
    preferIpAddress: true